### ISSUE TITLE
Modаl appears too fast

### ISSUE THREAD

**Issue by arsenydubrovin** [Vinzent03/tab-switcher#25]
Hi,
I often use `Ctrl+Tab` to switch between the last two tabs. But I noticed that when I press these keys quickly, modal appears for a short time and then disappears. It's a little annoying.

Maybe it would help to set a small delay before the modal appears, or maybe it would only appear when I release the `Tab` key while holding `Ctrl`.

I use the `Ctrl+Tab` hotkey for `Go to previous tab`. All settings except `Show modal` disabled.

Thanks for great plugin. This is what I was looking for!

**Comment by Vinzent03** [comment]
Great idea with only showing the modal when tab key is released, but ctrl is still pressed! I just implemented that and is available in the latest version.

**Comment by arsenydubrovin** [comment]
I just installed and tested the update. It works perfectly!

Thank you!
